version: '3.8'

services:
  db:
    image: postgres:15
    container_name: coveragex_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: coveragex
      POSTGRES_USER: appuser
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: coveragex_backend
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_USER=appuser
      - DB_PASSWORD=rootpassword
      - DB_NAME=coveragex
      - DB_PORT=5432
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: coveragex_frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API=http://backend:5000
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
